import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { api } from '../../lib/api'
import { buildNotAnalyzedOverview } from '../../test/projectOverviewFixtures'
import { CodeQualityProject } from './CodeQualityProject'
import { CodeQualityProjects } from './CodeQualityProjects'
import { ProjectOverviewPage } from './ProjectOverviewPage'

vi.mock('../../lib/api', () => ({ api: { listProjects: vi.fn(), listQualityGates: vi.fn(), createProject: vi.fn(), createProjectFromArchive: vi.fn(), getProject: vi.fn(), assignProjectGate: vi.fn(), startProjectAnalysis: vi.fn(), projectAnalysisStatus: vi.fn(), latestProjectAnalysis: vi.fn(), projectAnalyses: vi.fn(), projectOverview: vi.fn() } }))

const project = { id: 'p1', name: 'Synapse', key: 'synapse', sourceBinding: { kind: 'git' as const, value: 'https://example.com/repo.git', ref: 'main' }, defaultProfileByLang: {}, gateId: '', createdAt: null, latestAnalysis: null, latestJob: null }
const snapshot = { id: 'a1', createdAt: '2026-07-17T12:00:00Z', sourceRef: 'main', sourceCommit: 'abc123456789', gate: { passed: false, results: [] }, gateInfo: { key: 'synapse-way', name: 'Synapse way', source: 'default' as const }, issues: { total: 3, byKind: {}, bySeverity: { critical: 1, high: 1 }, byStatus: {} }, newCode: { previousId: '', counts: { total: 2, byKind: {}, bySeverity: { critical: 1 }, byStatus: {} }, rating: { security: 'E' as const, reliability: 'A' as const, maintainability: null } }, delta: null, measures: {}, coverage: null, duplication: { blocks: [], duplicatedLines: 0, totalLines: 10, files: 0 }, rating: { security: 'E' as const, reliability: 'B' as const, maintainability: 'A' as const, techDebtMinutes: 0, debtRatioPct: 0, linesOfCode: 10 } }
function renderList() { return render(<MemoryRouter><CodeQualityProjects /></MemoryRouter>) }

describe('Code Quality projects', () => {
  beforeEach(() => { vi.resetAllMocks(); vi.mocked(api.projectAnalysisStatus).mockResolvedValue(null); vi.mocked(api.listQualityGates).mockResolvedValue([]); vi.mocked(api.latestProjectAnalysis).mockResolvedValue(null); vi.mocked(api.projectAnalyses).mockResolvedValue({ items: [], next: null }); vi.mocked(api.projectOverview).mockResolvedValue(buildNotAnalyzedOverview()) })
  it('renders loading and empty states', async () => { vi.mocked(api.listProjects).mockReturnValue(new Promise(() => {})); const view = renderList(); expect(screen.getByText('Loading projects…')).toBeInTheDocument(); view.unmount(); vi.mocked(api.listProjects).mockResolvedValue([]); renderList(); expect(await screen.findByText('No code quality projects yet')).toBeInTheDocument() })
  it('retries a failed project list', async () => { vi.mocked(api.listProjects).mockRejectedValueOnce(new Error('Network error')).mockResolvedValue([]); renderList(); expect(await screen.findByText('Network error')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Retry' })); expect(await screen.findByText('No code quality projects yet')).toBeInTheDocument() })
  it('renders portfolio health from the enriched list without status fan-out', async () => { vi.mocked(api.listProjects).mockResolvedValue([{ ...project, latestAnalysis: snapshot }]); renderList(); expect(await screen.findByRole('heading', { name: 'Synapse' })).toBeInTheDocument(); expect(screen.getAllByText('Gate failed')).not.toHaveLength(0); expect(screen.getByLabelText('Security rating E')).toBeInTheDocument(); expect(screen.getByText('Open decision details')).toBeInTheDocument(); expect(api.projectAnalysisStatus).not.toHaveBeenCalled() })
  it('filters projects by search', async () => { vi.mocked(api.listProjects).mockResolvedValue([project, { ...project, id: 'p2', name: 'Other', key: 'other' }]); renderList(); await screen.findByRole('heading', { name: 'Synapse' }); fireEvent.change(screen.getByLabelText('Search projects'), { target: { value: 'missing' } }); expect(screen.getByText('No matching projects')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Clear filters' })); expect(screen.getByRole('heading', { name: 'Other' })).toBeInTheDocument() })
  it('adds a visible focus style to the archive picker', async () => { Object.defineProperty(HTMLElement.prototype, 'scrollIntoView', { configurable: true, value: vi.fn() }); vi.mocked(api.listProjects).mockResolvedValue([]); renderList(); fireEvent.click(await screen.findByRole('button', { name: /New project/i })); fireEvent.click(screen.getByRole('combobox', { name: 'Source kind' })); fireEvent.click(await screen.findByRole('option', { name: 'Upload archive' })); const picker = screen.getByRole('button', { name: /Drop an archive here or choose a file/i }); expect(picker).toHaveClass('focus-visible:outline-none', 'focus-visible:ring-2', 'focus-visible:ring-brand/60', 'focus-visible:ring-offset-2', 'focus-visible:ring-offset-bg') })
  it('creates and navigates to the shell', async () => { vi.mocked(api.listProjects).mockResolvedValue([]); vi.mocked(api.createProject).mockResolvedValue(project); vi.mocked(api.startProjectAnalysis).mockResolvedValue({ id: 'j1', engagementId: 'e1', target: project.sourceBinding.value, kind: 'git', status: 'running', stage: 'queued', progress: 0, error: '', startedAt: null, finishedAt: null, debugEvents: [] }); render(<MemoryRouter initialEntries={['/code-quality']}><Routes><Route path="/code-quality" element={<CodeQualityProjects />} /><Route path="/code-quality/projects/:key" element={<div>Project shell route</div>} /></Routes></MemoryRouter>); fireEvent.click(await screen.findByRole('button', { name: /New project/i })); fireEvent.change(screen.getByLabelText('Name'), { target: { value: 'Synapse' } }); fireEvent.change(screen.getByLabelText('Source'), { target: { value: 'https://example.com/repo.git' } }); fireEvent.click(screen.getByRole('button', { name: /Create and analyze/i })); await waitFor(() => expect(api.createProject).toHaveBeenCalledWith(expect.objectContaining({ key: 'synapse' }))); expect(api.startProjectAnalysis).toHaveBeenCalledWith('synapse'); expect(await screen.findByText('Project shell route')).toBeInTheDocument() })
  it('navigates to the created project when auto-start fails', async () => { vi.mocked(api.listProjects).mockResolvedValue([]); vi.mocked(api.createProject).mockResolvedValue(project); vi.mocked(api.getProject).mockResolvedValue(project); vi.mocked(api.startProjectAnalysis).mockRejectedValue(new Error('Scanner unavailable')); render(<MemoryRouter initialEntries={['/code-quality']}><Routes><Route path="/code-quality" element={<CodeQualityProjects />} /><Route path="/code-quality/projects/:key" element={<CodeQualityProject />}><Route index element={<ProjectOverviewPage />} /></Route></Routes></MemoryRouter>); fireEvent.click(await screen.findByRole('button', { name: /New project/i })); fireEvent.change(screen.getByLabelText('Name'), { target: { value: 'Synapse' } }); fireEvent.change(screen.getByLabelText('Source'), { target: { value: 'https://example.com/repo.git' } }); fireEvent.click(screen.getByRole('button', { name: /Create and analyze/i })); expect(await screen.findByRole('heading', { name: 'Synapse' })).toBeInTheDocument(); expect(screen.getByText('Scanner unavailable')).toBeInTheDocument(); expect(await screen.findByText('No completed analysis yet')).toBeInTheDocument(); expect(screen.getByRole('button', { name: /Run first analysis/i })).toBeInTheDocument() })
  it('renders an honest project shell empty state', async () => { vi.mocked(api.getProject).mockResolvedValue(project); render(<MemoryRouter initialEntries={['/code-quality/projects/synapse']}><Routes><Route path="/code-quality/projects/:key" element={<CodeQualityProject />}><Route index element={<ProjectOverviewPage />} /></Route></Routes></MemoryRouter>); expect(await screen.findByRole('heading', { name: 'Synapse' })).toBeInTheDocument(); expect(await screen.findByText('No completed analysis yet')).toBeInTheDocument(); expect(screen.getByLabelText('Coverage report (optional)')).toHaveAttribute('type', 'file') })
})
