package sca

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/KKloudTarus/synapse-ce/internal/domain/importedsbom"
	"github.com/KKloudTarus/synapse-ce/internal/domain/sbom"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
	"github.com/KKloudTarus/synapse-ce/internal/usecase/ports"
)

// ImportSBOM ingests a client-supplied CycloneDX SBOM (consultancies receive
// client SBOMs) as the engagement's scan result, so its components are visible,
// license-summarized, exportable (SPDX), and sealed into the evidence chain. It does
// NOT run vulnerability detection on the imported components – that reuses the
// post-SBOM half of the scan pipeline and is a follow-up; importing makes the
// client's inventory a first-class, attested artifact today. Audited.
func (s *Service) ImportSBOM(ctx context.Context, actor string, tenantID, engagementID shared.ID, data []byte) (*ScanResult, error) {
	return s.ImportSBOMFile(ctx, actor, tenantID, engagementID, importedsbom.DefaultFilename, data)
}

// ImportSBOMFile ingests a named client-supplied CycloneDX SBOM.
func (s *Service) ImportSBOMFile(ctx context.Context, actor string, tenantID, engagementID shared.ID, filename string, data []byte) (*ScanResult, error) {
	if _, err := s.engagements.GetByIDInTenant(ctx, tenantID, engagementID); err != nil {
		return nil, fmt.Errorf("load engagement: %w", err)
	}
	parsed, err := parseCycloneDX(data)
	if err != nil {
		return nil, err
	}
	now := s.clock.Now()
	comps, target := parsed.Components, parsed.TargetRef
	if target == "" {
		target = "imported-sbom"
	}
	doc := &sbom.SBOM{
		TargetRef:        target,
		Source:           "imported-cyclonedx",
		GeneratorVersion: parsed.GeneratorVersion,
		Components:       comps,
		Dependencies:     parsed.Dependencies,
		Raw:              append([]byte(nil), data...),
		Audit:            shared.Audit{CreatedAt: now, UpdatedAt: now},
	}
	resolved := 0
	for _, c := range comps {
		if sbom.IsResolvedVersion(c.Version) {
			resolved++
		}
	}
	res := &ScanResult{
		Target:          target,
		SBOM:            doc,
		LicenseCoverage: sbom.ComputeLicenseCoverage(comps),
		Completeness: ports.Completeness{
			ComponentsTotal:    len(comps),
			ComponentsResolved: resolved,
			Confident:          true,
			Warning:            "imported client SBOM (not generated by Synapse); vulnerability detection not run on import",
		},
		ToolVersions: map[string]string{"import": "cyclonedx"},
		// Pin a snapshot marker so SPDX export stays byte-reproducible (scanTime parses
		// the timestamp after the last '@').
		VulnDBSnapshot: "imported@" + now.UTC().Format(time.RFC3339),
		// Anchor the evidence seal to the exact SBOM that was imported.
		Manifest: ports.ScanManifest{SBOMSHA256: hashHex(data)},
	}

	if _, err := s.sealEvidence(ctx, actor, engagementID, now, res, ""); err != nil {
		return nil, err
	}

	if s.importedSBOM != nil {
		if strings.TrimSpace(filename) == "" {
			filename = importedsbom.DefaultFilename
		}
		record := importedsbom.Record{
			ID:              s.importedSBOMID(data),
			TenantID:        tenantID,
			EngagementID:    engagementID,
			Filename:        filename,
			Format:          importedsbom.FormatCycloneDX,
			SpecVersion:     parsed.SpecVersion,
			TargetRef:       target,
			ComponentCount:  len(comps),
			DependencyCount: len(parsed.Dependencies),
			SHA256:          hashHex(data),
			RawJSON:         append([]byte(nil), data...),
			CreatedBy:       actor,
			CreatedAt:       now,
		}
		if err := s.importedSBOM.SaveActive(ctx, record); err != nil {
			return nil, fmt.Errorf("save imported SBOM artifact: %w", err)
		}
	}

	if s.results != nil {
		out, err := json.Marshal(res)
		if err != nil {
			return nil, fmt.Errorf("encode imported result: %w", err)
		}
		if err := s.results.SaveResult(ctx, engagementID, out); err != nil {
			return nil, fmt.Errorf("save imported result: %w", err)
		}
	}
	_ = s.audit.Record(ctx, ports.AuditEntry{
		Actor: actor, Action: "sca.sbom.imported", Target: target,
		Metadata: map[string]string{"engagement": engagementID.String(), "components": strconv.Itoa(len(comps)), "dependencies": strconv.Itoa(len(parsed.Dependencies)), "format": "cyclonedx", "spec_version": parsed.SpecVersion, "sha256": hashHex(data)},
		At:       now,
	})
	return res, nil
}

func (s *Service) importedSBOMID(data []byte) shared.ID {
	if s.ids != nil {
		return s.ids.NewID()
	}
	h := hashHex(data)
	if len(h) > 16 {
		h = h[:16]
	}
	return shared.ID("imported-sbom-" + h)
}

// ImportedSBOMMetadata returns safe metadata for the active imported SBOM.
func (s *Service) ImportedSBOMMetadata(ctx context.Context, tenantID, engagementID shared.ID) (importedsbom.Metadata, error) {
	if _, err := s.engagements.GetByIDInTenant(ctx, tenantID, engagementID); err != nil {
		return importedsbom.Metadata{}, fmt.Errorf("load engagement: %w", err)
	}
	if s.importedSBOM == nil {
		return importedsbom.Metadata{}, fmt.Errorf("imported SBOM for engagement %s: %w", engagementID, shared.ErrNotFound)
	}
	record, err := s.importedSBOM.LatestByEngagement(ctx, tenantID, engagementID)
	if err != nil {
		return importedsbom.Metadata{}, err
	}
	return record.Metadata(), nil
}

// ---- minimal CycloneDX JSON parser (components only) ----

type parsedCycloneDX struct {
	SpecVersion      string
	TargetRef        string
	GeneratorVersion string
	Components       []sbom.Component
	Dependencies     []sbom.Dependency
}

type cdxBOM struct {
	BOMFormat   string `json:"bomFormat"`
	SpecVersion string `json:"specVersion"`
	Metadata    struct {
		// Tools is the legacy array [{vendor,name,version}] (<=1.4) OR the object {components:[...]} (1.5+);
		// kept raw so a modern document does not fail the whole decode on this optional field. Parsed by
		// cdxGeneratorVersion.
		Tools     json.RawMessage `json:"tools"`
		Component cdxComponent    `json:"component"`
	} `json:"metadata"`
	Components   []cdxComponent  `json:"components"`
	Dependencies []cdxDependency `json:"dependencies"`
}

type cdxComponent struct {
	Group    string `json:"group"`
	Type     string `json:"type"`
	Name     string `json:"name"`
	Version  string `json:"version"`
	PURL     string `json:"purl"`
	BOMRef   string `json:"bom-ref"`
	Scope    string `json:"scope"` // CycloneDX scope: required|optional|excluded
	Supplier struct {
		Name string `json:"name"`
	} `json:"supplier"`
	Licenses []struct {
		License struct {
			ID   string `json:"id"`
			Name string `json:"name"`
			URL  string `json:"url"`
		} `json:"license"`
		Expression string `json:"expression"`
	} `json:"licenses"`
}

type cdxDependency struct {
	Ref       string   `json:"ref"`
	DependsOn []string `json:"dependsOn"`
}

// supportedCDXSpecVersions are the CycloneDX 1.x spec versions the importer accepts. The fields Synapse
// reads (bomFormat, components with purl/version/licenses, metadata.component, dependencies) are
// stable across these versions and CycloneDX is backward-tolerant within 1.x, so a 1.5/1.6 document parses
// the same as a 1.4 one. Accepting 1.5/1.6 lets Synapse ingest what current Syft/Trivy/cdxgen emit by
// default, and re-import its own CycloneDX 1.6 export.
var supportedCDXSpecVersions = map[string]bool{"1.4": true, "1.5": true, "1.6": true}

func supportedCDXSpecVersion(v string) bool {
	return supportedCDXSpecVersions[strings.TrimSpace(v)]
}

// parseCycloneDX decodes a CycloneDX JSON document into domain components + the
// target name from metadata. Rejects a non-CycloneDX or empty document.
func parseCycloneDX(data []byte) (parsedCycloneDX, error) {
	var bom cdxBOM
	if err := json.Unmarshal(data, &bom); err != nil {
		return parsedCycloneDX{}, fmt.Errorf("%w: invalid CycloneDX JSON: %v", shared.ErrValidation, err)
	}
	if !strings.EqualFold(bom.BOMFormat, "CycloneDX") {
		return parsedCycloneDX{}, fmt.Errorf("%w: not a CycloneDX document (bomFormat=%q)", shared.ErrValidation, bom.BOMFormat)
	}
	if !supportedCDXSpecVersion(bom.SpecVersion) {
		return parsedCycloneDX{}, fmt.Errorf("%w: unsupported CycloneDX specVersion %q (supported: 1.4, 1.5, 1.6)", shared.ErrValidation, bom.SpecVersion)
	}
	if len(bom.Components) == 0 {
		return parsedCycloneDX{}, fmt.Errorf("%w: CycloneDX document has no components", shared.ErrValidation)
	}
	out := make([]sbom.Component, 0, len(bom.Components)+1)
	if metadataComponentHasIdentity(bom.Metadata.Component) {
		if comp, ok := cdxComponentToDomain(bom.Metadata.Component); ok {
			comp.FirstParty = true
			out = append(out, comp)
		}
	}
	for _, c := range bom.Components {
		if comp, ok := cdxComponentToDomain(c); ok {
			out = append(out, comp)
		}
	}
	if len(out) == 0 {
		return parsedCycloneDX{}, fmt.Errorf("%w: no named components in the SBOM", shared.ErrValidation)
	}
	deps := make([]sbom.Dependency, 0, len(bom.Dependencies))
	for _, d := range bom.Dependencies {
		ref := strings.TrimSpace(d.Ref)
		if ref == "" {
			continue
		}
		dependsOn := make([]string, 0, len(d.DependsOn))
		for _, dep := range d.DependsOn {
			if dep = strings.TrimSpace(dep); dep != "" {
				dependsOn = append(dependsOn, dep)
			}
		}
		deps = append(deps, sbom.Dependency{Ref: ref, DependsOn: dependsOn})
	}
	return parsedCycloneDX{
		SpecVersion:      bom.SpecVersion,
		TargetRef:        bom.Metadata.Component.Name,
		GeneratorVersion: cdxGeneratorVersion(bom.Metadata.Tools),
		Components:       out,
		Dependencies:     deps,
	}, nil
}

func metadataComponentHasIdentity(c cdxComponent) bool {
	return strings.TrimSpace(c.PURL) != "" || strings.TrimSpace(c.Version) != "" || len(c.Licenses) > 0
}

func cdxComponentToDomain(c cdxComponent) (sbom.Component, bool) {
	if strings.TrimSpace(c.Name) == "" {
		return sbom.Component{}, false
	}
	name := c.Name
	if c.Group != "" && strings.HasPrefix(c.PURL, "pkg:maven/") {
		name = c.Group + ":" + c.Name
	}
	comp := sbom.Component{Name: name, Version: c.Version, PURL: c.PURL}
	// Preserve the client's declared supplier (NTIA element, tagged "declared" as it is untrusted client input);
	// else derive it from the PURL namespace ("derived").
	comp.Supplier, comp.SupplierSource = sbom.SupplierWithSource(c.Supplier.Name, c.PURL)
	// No on-disk location for an imported component; the CycloneDX scope still
	// classifies dev/excluded (excluded -> development).
	comp.Scope = sbom.ClassifyScope("", c.Scope)
	for _, lc := range c.Licenses {
		switch {
		case lc.License.ID != "":
			comp.Licenses = append(comp.Licenses, sbom.License{SPDXID: lc.License.ID})
		case lc.License.URL != "":
			comp.Licenses = append(comp.Licenses, sbom.License{Name: lc.License.URL})
		case lc.License.Name != "":
			comp.Licenses = append(comp.Licenses, sbom.License{Name: lc.License.Name})
		case lc.Expression != "":
			comp.Licenses = append(comp.Licenses, sbom.License{Name: lc.Expression})
		}
	}
	if len(comp.Licenses) > 0 {
		comp.LicenseSource = "sbom"
		comp.LicenseConfidence = "declared"
	}
	return comp, true
}

// cdxMaxToolsBytes bounds the raw metadata.tools value before parsing: a real tools list is a handful of
// entries, so a larger value is an implausible/adversarial blob and yields no generator string (it never
// rejects the document, since GeneratorVersion is optional) rather than decoding a huge transient slice.
const cdxMaxToolsBytes = 64 << 10

// cdxMaxGeneratorVersionChars caps the untrusted generator string before it is stored, sealed into the
// import manifest, and shown, so a pathological tools.name/version cannot amplify into those sinks.
const cdxMaxGeneratorVersionChars = 256

// cdxGeneratorVersion extracts a "name/version" for the SBOM's generating tool from metadata.tools, which
// has TWO shapes across CycloneDX versions: the legacy array [{vendor,name,version}] (<=1.4) and the object
// {components:[{name,version}], services:[...]} (1.5+). It tries both and never errors – a tools value it
// cannot read just yields "", so a modern document is not rejected over this optional field.
func cdxGeneratorVersion(raw json.RawMessage) string {
	if len(raw) == 0 || len(raw) > cdxMaxToolsBytes {
		return ""
	}
	type cdxTool struct {
		Vendor  string `json:"vendor"`
		Name    string `json:"name"`
		Version string `json:"version"`
	}
	format := func(t cdxTool) string {
		name := strings.TrimSpace(t.Name)
		if name == "" {
			name = strings.TrimSpace(t.Vendor)
		}
		version := strings.TrimSpace(t.Version)
		var s string
		switch {
		case name == "":
			s = version
		case version == "":
			s = name
		default:
			s = name + "/" + version
		}
		if len(s) > cdxMaxGeneratorVersionChars { // cap the untrusted string (rune-safe) before it flows onward
			if r := []rune(s); len(r) > cdxMaxGeneratorVersionChars {
				s = string(r[:cdxMaxGeneratorVersionChars])
			}
		}
		return s
	}
	var arr []cdxTool // legacy array form
	if err := json.Unmarshal(raw, &arr); err == nil {
		if len(arr) > 0 {
			return format(arr[0])
		}
		return ""
	}
	var obj struct { // 1.5+ object form: tools.components[]
		Components []cdxTool `json:"components"`
	}
	if err := json.Unmarshal(raw, &obj); err == nil && len(obj.Components) > 0 {
		return format(obj.Components[0])
	}
	return ""
}

func hashHex(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}
